update=11.04.2018 23:40:42
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=D:/Documents/KiCad-Projects/UserLibraries
[eeschema/libraries]
LibName1=74xx_new
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/allegro
LibName8=C:/Program Files/KiCad/share/kicad/library/Altera
LibName9=C:/Program Files/KiCad/share/kicad/library/AMS1117-3V3
LibName10=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName11=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName12=C:/Program Files/KiCad/share/kicad/library/atmel
LibName13=C:/Program Files/KiCad/share/kicad/library/audio
LibName14=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName15=C:/Program Files/KiCad/share/kicad/library/bbd
LibName16=C:/Program Files/KiCad/share/kicad/library/bosch
LibName17=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName18=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName19=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName20=C:/Program Files/KiCad/share/kicad/library/conn
LibName21=C:/Program Files/KiCad/share/kicad/library/contrib
LibName22=C:/Program Files/KiCad/share/kicad/library/cypress
LibName23=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName24=C:/Program Files/KiCad/share/kicad/library/device
LibName25=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName26=C:/Program Files/KiCad/share/kicad/library/diode
LibName27=C:/Program Files/KiCad/share/kicad/library/display
LibName28=C:/Program Files/KiCad/share/kicad/library/dsp
LibName29=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName30=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName31=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName32=C:/Program Files/KiCad/share/kicad/library/gennum
LibName33=C:/Program Files/KiCad/share/kicad/library/graphic
LibName34=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName35=C:/Program Files/KiCad/share/kicad/library/hc11
LibName36=C:/Program Files/KiCad/share/kicad/library/infineon
LibName37=C:/Program Files/KiCad/share/kicad/library/intel
LibName38=C:/Program Files/KiCad/share/kicad/library/interface
LibName39=C:/Program Files/KiCad/share/kicad/library/intersil
LibName40=C:/Program Files/KiCad/share/kicad/library/ir
LibName41=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName42=C:/Program Files/KiCad/share/kicad/library/leds
LibName43=C:/Program Files/KiCad/share/kicad/library/LEM
LibName44=C:/Program Files/KiCad/share/kicad/library/linear
LibName45=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName46=C:/Program Files/KiCad/share/kicad/library/logo
LibName47=C:/Program Files/KiCad/share/kicad/library/maxim
LibName48=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName49=C:/Program Files/KiCad/share/kicad/library/memory
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName52=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName53=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName54=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName55=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName56=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName57=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName58=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName59=C:/Program Files/KiCad/share/kicad/library/modules
LibName60=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName61=C:/Program Files/KiCad/share/kicad/library/motorola
LibName62=C:/Program Files/KiCad/share/kicad/library/motors
LibName63=C:/Program Files/KiCad/share/kicad/library/msp430
LibName64=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName65=C:/Program Files/KiCad/share/kicad/library/nxp
LibName66=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName67=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName68=C:/Program Files/KiCad/share/kicad/library/opto
LibName69=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName70=C:/Program Files/KiCad/share/kicad/library/philips
LibName71=C:/Program Files/KiCad/share/kicad/library/power
LibName72=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName73=C:/Program Files/KiCad/share/kicad/library/powerint
LibName74=C:/Program Files/KiCad/share/kicad/library/pspice
LibName75=C:/Program Files/KiCad/share/kicad/library/references
LibName76=C:/Program Files/KiCad/share/kicad/library/regul
LibName77=C:/Program Files/KiCad/share/kicad/library/relays
LibName78=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName79=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName80=C:/Program Files/KiCad/share/kicad/library/sensors
LibName81=C:/Program Files/KiCad/share/kicad/library/silabs
LibName82=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName83=C:/Program Files/KiCad/share/kicad/library/stm8
LibName84=C:/Program Files/KiCad/share/kicad/library/stm32
LibName85=C:/Program Files/KiCad/share/kicad/library/supertex
LibName86=C:/Program Files/KiCad/share/kicad/library/switches
LibName87=C:/Program Files/KiCad/share/kicad/library/texas
LibName88=C:/Program Files/KiCad/share/kicad/library/transf
LibName89=C:/Program Files/KiCad/share/kicad/library/transistors
LibName90=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName91=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName92=C:/Program Files/KiCad/share/kicad/library/valves
LibName93=C:/Program Files/KiCad/share/kicad/library/video
LibName94=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName95=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName96=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName97=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName98=C:/Program Files/KiCad/share/kicad/library/zetex
LibName99=C:/Program Files/KiCad/share/kicad/library/Zilog
